* The Skin Crawls! (temporary title)

** Original Idea
Takes place in 1920s San Antonio. A more open and free scenario. Deals with an ancient one that is microscopic, it 'infects' a person or animal with a sort of disease similiar to mange. Causes all hair to fall out and skins to become rough, scab-like, and drives them utterly insane (see Sarcoptic Mange, or 'scabies').

The backstory involves a meteor falling to the ground close to San Antonio. The San Antonio Astronomy Association, namely Aline Carter (a real person, see the Carter house), observed this first. A homeless man named Jasper Smith was camping out with this faithful dog, when he saw the meotorite landed near. Believing that he might get a finders award for bringing it back, he sets off to find where it landed. This metorite as it happens, contains a remanant of a Great Old One named Xhulchin-bara: a tiny microscopic being that emits a contagous spell.

This is the beginning of the myth of the chupacabra, as it infected a pack of dogs first that went on to kill livestock and later infect other dogs. These roam the streets at night attacking people. Another person infected early on was a vagabond.
