* Taken Before the Flood

*** The Rising Waters of Terror!

** INFORMATION

An open source community adventure - Created by: Chris Hardee

** INTRODUCTION

*** Inspiration

Taken Before the Flood was envisioned when reading a blog post on tips for Keepers. In a section on things NOT to do as a Keeper, one of them mentioned not to get investigators anywhere near water. The poster explained this due to the fact that investigators never put any skill points into Swimming and thus always fail critical rolls when in the water. When I read this, naturally, I invisioned a water scenario. I think that bit of advise could apply towards a multitude of skills (driving perhaps), something about investigators constantly being dragged underwater inspired me. Disaster movies additionally, with lots of dramas being amplified by the chaos and peril of the event.
I think the investigator peril is central to the adventure, however. To help illustrate this point, here is a quote from an inspirational keeper: "I want you to play to lose. I want you to put yourself in situations where bad shit happens. I want you to put yourself in situations where you don't get what you want and let the story come out of that and see what happens."

*** Length

Hopefully one session if investigators blaze through it, though more likely two to three. The span of the adventure will take place in one location over the span of three in-game days.

*** Setting

This scenario was envisioned for the Call of Cthulhu classic 1920s era, though with some changes here and there would adapt to a modern or gaslight scenario. Common problems like smart phones can be cleverly avoided due to the sheer amount of electronics-destroying rain, additionally the final battle could potentially be much more difficult due to the disarmament of the local fort. Tips for adapting this scenario to other eras are included in the appendix.

** KEEPER INFORMATION

Taken before the Flood begins with the central artifact already being secreted away and a terrifying ritual already begun. A Keeper may wish to play through the initial spark, the Author felt that bad things already happening without the investigators understanding the implications adds to the dramatic tension.

*** Background

At approximately 7pm yesterday evening: a book of the rarest sort, /Canticum de Abyssi/ (author unknown), was taken from Yanaguana Society's private library, by a Ms. Davos. Its disappearance hasn't been realized yet, though that's soon to change. Upon taking the book the thief headed north to the small resort town of Newspring. Upon arriving she immediately checked into the town's one and only resort Hotel, the Menger, and began performing a complex ritual, derived from the stolen book. In the wee hours of the morning, immediately upon completing the ritual, a portal opened up in the skies above the hotel. The ritual, ultimately, was to call forth the Great Old One: Cthulhu. Cthulhu, being dead and dreaming in R'leyth, may be brought for from the sea and due to Newspring being about 300 miles from the nearest ocean; if Cthulhu cannot be called directly from the depths of the ocean: the ocean will come with it. The ritual is particularly disruptive to reality and the Great Old One will not be happy being pulled from slumber and return soon afterwards. This portal is connected to the sunken dead city of R'leyth, deep below the ocean, and it is growing exponentially. First will be light rain, then heavy rains, followed by a torrent of rain the likes which have never seen before. Hundreds Deep Ones, horrible fish-like monsters, will be pulled through and search for sacrifices to aid in the crossing. The final stage will be a great sea column, a virtual tower of water, large enough for Cthulhu to crossover as the the ritual completes. The rain will not stop until the ritual is finished unless the Great Old One is dismissed, Cthulhu's non-materialized form has been disrupted, or Cthulhu finally materializes. In which case Cthulhu will drag the now sunken city back with it into the depths of the ocean, so it may rejoin its slumber.

*** Menger Hotel

Built before the civil war era when the city was a small frontier town. The building is primarily white limestone with classical features. While suffering damage from the civil war, it has been slowly expanded to add additional floors and wings. There are many legends of heroes and dignitaries, including a president or two staying there. It also has as many ghosts stories. Ghost sightings are common and backed up by a very real story of a maid who was murdered and buried at the hotel's expense.

*** /Canticum de Abyssi/

The book used for the calling ritual is filled with terrifying Mythos power. An ancient book, it is mostly sheets of papyrus sandwiched between hand carved wooden slats. It was closely guarded by the Yanaguana Society, as it is great sought after by Cthulhu cults spanning the global. Written in Latin, with curious mentions to an emperor that doesn't exists in known history books, it speaks on giving birth to an eternal wellspring of water to the land, with "The Great One" as its shepherd via a series of rituals within rituals. The author had the intelligence to see deep mechanics at play, the underlying forces behind the madness, to create a hyper condensed calling forth of Cthulhu. To intelligent investigators, they too can understand these inner workings, and with that be able to reverse the machinations to dismiss Cthulhu. The book is quite fragile and clumsy or unlucky investigators carrying the book can render the book wet and ruined if not careful, though it could be easily argued that this book being destroyed is a win for humanity.
Understanding how to perform the ritual is fairly spelled out; however, only Investigators making a successful *Latin* skill check, hard *INT*, or hard *Library Use* roll (whichever is highest) will understand its full sinister implications and gain the dismissal spell. Making the skill checks or not, reading this book has its costs (SAN 1/1D6). Investigators failing the Sanity check will sincerely believe this book can be used to help humanity by creating a portal of water and life anywhere on the earth, as Ms. Davos believed. Investigators wanting to comprehend its full contents will need an entire week to study it. Reading the entire book will add 8 points to an investigators *Cthulhu Mythos*, costs 1D8 Sanity, and contains the Call Cthulhu spell (it's known as The Ritual of Life if they've failed their Sanity check) and Dismiss Cthulhu spell (if skill checks are passed).

*** Flow of time

The scenario is broken up into three acts with sub sections in each marking important events. Though time is on a schedule, Keepers are advised to be leiniant on time and only advance the "clock" when a natural break occurs. Concordantly, players should realize a sense of urgency and not run off their rooms and read dusty tomes for three days.

*** Flooding

As noted in the act's subsections, the Hotel is slowly flooding along with the city it inhabits. As such, parts of the hotel begin to be submerged. The Keeper may indicate this on the map handout by shading in the flooded and submerged areas with a pencil. A flooded area means enough water has gathered to make it difficult to walk and a submerged area will require holding ones breath. Investigators my attempt to stem the flooding by barricading doors or stairs which will be only slightly effective in keeping the water at bay, rickety wooden hotel doors are not naval bulk-heads.

*** Optional Rules for Hypothermia

Wading in the water for an extended time can start to cause hypothermia on the investigator. Keeper may optionally keep track of how long a player has been in the water and how long they've been in their wet clothes. After four hours of being in water and/or in wet clothes, require the investigators to make a Constitution check and after each additional hour they don't get dry and warm. Failing this check will cause a loss of 1D4 HP and Magic points, along with the investigator becoming fatigued and shivering uncontrollably. If the investigator fails to get dry and warm each additional failed Constitution roll will incur an additional 1D4. This cumulative penalty resets once they're safe, dry, and warm. It should be noted that places to find warmth will be scarce, save for another living human body. It is hoped the investigators will not be trepidacious of bedding with a fellow investigator when survival is on the line.

*** Deep One Encounters

Once Deep Ones appear on the second day, they will continuously spawn in the water and attempt to hunt down humans. Deep Ones can be used to push the action forward if Investigators are dawdling. If investigators are making a racket or carelessly wandering the halls the keeper may call for a group *LUCK* roll, failing that a Deep One will arrive in 1D6 rounds.

Refer to /Call of Cthulhu: Keeper Rulebook/ for Deep One's stats.

** NON-PLAYER CHARACTERS

*** Staff

*Ernesto Manacavas:* Hotel owner and historian. A small man wearing glasses and sporting a graying beard. Though the owner, Ernesto leaves managing to his hired administer Mr. Fines. Instead Ernesto haunts the hotel checking to see everything is in order and properly dusted and will regale passerbys with random tidbits of history and trivia. Usually quiet, but when asked about a certain fixture of the hotel or espcially a ghost-sighting, will rattle off for hours without break with every minutia of detail about it. Though certainly charming once he gets worked up, eventually everyone fatigues at his sermons and will eventually politely excuse themselves once a rare break in his speech happens. Ernesto never takes offense to this, will smile, bid them forewell, and continue on his way.

Ernesto rarely finds himself distraught or panicked, as would happen when the upcoming events would unfold; alas, when this happens he takes to drink badly. Hobbies of Ernesto's include fine wines and the supernatural, in fact, he is quite in tune with the mythos having encounters it early in his life but never fully understanding, or believing, it himself. He alone intuits that Ms. Davos is behind the events that are to unfold.

Ernesto is aware of anyone touched by or has knowledge of Cthulhu Mythos. Any investigator who has some points in Cthulhu Mythos speaks to Ernesto, he might make a comment about it. If pressed on it, investigators should make a *Cthulhu Mythos* roll. If successful the investigators senses it back. He won't speak anymore on the subject.

*Henry Fines:* Hotel administer and a bit of a prickly pear. His duties involve berating staff, tending to the seemingly endless paperwork and phone calls, and keeping Ernesto from boring his important guests.
When times become dire at the hotel, he runs on raw instinct. This can make for a bad encounter if confronted.

*Charles the Bellhop:* The hotel's favorite bellhop. Helping the party upon arrival and when flood comes, can be a valuable ally. He plans on joining the Navy once he's earned enough for travel, but he carries with him a sense of duty to maintain the peace.

*** Travelers & Residents of the hotel

*Julia Davos:* The caller of Cthulhu. Pale with shoulder-length red hair, she looks quite tired when the investigators meet her though she would be quite beautiful otherwise. A former member of the Yanaguana Society, she has been driven insane by years of Mythos investigations and of reading /Canticum de Abyssi/. She truly believes she has found a way to help humanity out by bringing water and life to places where there is none and thus completes the ritual. She hates the Yanaguana Society, believing them to be fools who would squander all the knowledge and wisdom the mythos can reveal. She is sharp witted and knows full well the loss of life and destruction the summoning will bring, yet she hopes in the aftermath the Yanaguana Society will be wiped out and the region will renewed with a bounty of water and life. She is unfortunately only correct in the former of these assumptions.

*Alfred Hickenthorpe:* A charlatan of an inventor. Claims to have invented a device that uses the principles of radio wave transmission to harness unlimited energy. At first he attempted to understand the basic principles of radio waves from a few books on Marconi: he envisioned capturing transmitted energy from many sources in nature like the sun, or plants, or even 'the spiritual realm' (Tesla tried and failed to, up to the point of his death, to create a reliable source of wireless energy transmission, though Tesla's ideas were far more grounded in science and experimentation). The ideas went further in somehow 'transmuting' this infinite source of power to control the weather or creating a weapon to strike down anyone from afar. He was no engineer though and attempts to build such a device failed miserably. Nonetheless, he read enough and was a sharp enough talker to convince fools to invest in his ideas. Always trying to scrounge up investor money, he stays at the Menger trying to hawk his ideas. He is presented as a red herring if investigators believe his talk of controlling the weather. He carries in his luggage a 'prototype' that is little more than random electronic parts soldered and taped together.

*Lillian and Ronald Pierce:* Oil was and is a huge commodity for Texas and the nation, and Ronald Pierce owns a fair share of it. He recently finished up an oil deal that will increase his profits handsomely though he feels he could have held out and gotten a better deal. Though to most he is considered greedy, egotistical, and selfish the only thing he truly cares about beyond money is his daughter, Lillian. Lillian is 15 and is traveling with her father on his instance to learn business and negotiation, she is easily bored but enjoys card games and sleight of hand tricks. Quite unlike her father and despite being forever spoiled: she is friendly, charming, sharp. Only in a game of poker are all bets off.

*Peter King:* An insurance salesman, he's been recently informed of his failing health. He's decided to rest at the hotel for a week to try and feel better. A light sleeper, he asks the hotel clerk for sleeping aids to sleep through the storm. If acquired he will fall asleep and drown as the water fills his first floor room.

*Miriam Pell:* Woman trapped in the elevator shaft late on the second night. Miriam is under a curse it seems: only having recently discovered her husband with another woman and losing a great deal of her upper class lifestyle after he shut her out, she decided to check into the Menger hotel to her some means of recovery. Unfortunately she is having the worst of luck. On the second night she falls finds herself trapped in the elevator shaft: she attempted to flee through a small grate in the hallway after hearing screams coming around the hall.

** PLAYER CHARACTERS

*** Player Hooks

There is a certain amount of adventurous disbelief on account of the player's motivations to keep them in a hotel that seems to be slowly sinking. In a town of this size, there doesn't exist any sort of emergency procedures in case of a flood. Provided below are a couple of player hooks to for their character in this scenario:
- *Traveler:* A random stranger on a train looking to take a relaxing stay, potentially after a sanity-draining adventure.
- *Yanaguana Society Member:* An investigator tasks with finding the book by the Yanaguana Society, in addition to who, and more importantly, why?
- *Bellhop:* Works at the hotel, perhaps is a new to the town and newly hired. Staff is offered, for a fee, to stay in a small staff room. Knows the general layout and has a few useful keys too. Begins with the map handout, emulating the map in their heads.
- *Tortured Writer:* Has lived at the hotel for the past two months, attempting to write their next great novel after their previous novel became a runaway sensation. Writers block and pressure from the publisher has left this writer in a deep depression.

Sample character sheets are provided in the Appendix.

**** TODO Add in sample character sheets

*** Bringing the Party Together

Travelers on the train are seated next to each and, though potentially strangers, it's commonly known that one can save a good deal of money if two people stay in one room and decide to strike up a conversation with one another. The hotel is visible from the train station and any station staff will happily direct them. Long term guests of the hotel frequently rely on trusted staff (Player characters, employed by the hotel) for special requests: alcohol, cigarettes, maybe even a narcotic or two.

Rain has been coming down in this since late last night.

** ACT 1 THE CALM BEFORE THE STORM

*** Getting to the hotel

Investigators walking to the hotel without an umbrella notice that the rainwater has a distinctly briny taste to it. Investigators can make an *INT* check to note that this is highly unusual (water evaporates from oceans without its salt content). Unequipped investigators could spend time shopping now as there are general stores around the plaza, a Keeper could suggest the meeting/checkin times are a few hours away.

*** Arrival and Checking in

Investigators arriving in will be greeted with a lavish lobby with Victorian sensibilities but with a tastefully modern decor. Music plays through an electric gramaphone. Since various people are checking in, quite a few people are milling out the lobby chatting and laughing. This would be a good time to introduce some of the NPCs.

Travelers likely already a room booked for them, but if not previously discussed: now would be a good time to figure out room arrangements. Two can share a room and will be placed in the east wing on the third floor. Single rooms will be placed on the second floor on the west wing above the lobby. Suites are also available for a higher cost and those with a *Credit Rating* of 60% or above. Players can make arragements over payments and IOUs; however, keep in mind that they'll never get a chance to square up their bills.

Players approaching the counter will be greeted by Mr. Fines. For investigators with 40% or above *Credit Rating* or *APP* above 12, check-in goes by smoothly. Investigators with lower credit ratings may need to roll a *Credit Rating* check, failing that a *Charm* roll to convince Mr. Fines they're on the level. Investigators turned away may still stay in the hotel provided they're willing to bunk with someone who does pass. If all investigators fail, Keeper may openly ask players how they expected to get a room at a nice hotel when they're all dressed as hobos, that being said Fines does provide an /Economy Suite/ for even the shadiest of characters: essentially an empty staff room.

Players asking for a map of the local area or a map of the hotel will be handed the hotel-map from the handouts. Fines might highlight some areas of interest nearby to checkout, "once the rain clears up". Anything he highlights will be closed today and are of no use to the player in this adventure. Each player staying in a room will receive a key and Fines will call for a bellhop to show investigators up to their rooms.

*** Heading up

Players are shown up to their room by a bellhop named Charles, who will become more familiar as the events unfold. Charles is obviously fishing for tips and will enthusiastically inform the player about breakfast/lunch/dinner in the dining hall, location of the pool/bar/garden, and will mention that whenever it rains all day a rainyday ball will usually be held late at night.
The rooms rooms are a comfortable victorian affair, though players with a single room will note its small size. Suites are larger with a few more furishings. West windows look out to the square.

Those saddled with the /Economy Suite/ will give Charles a bit of a chuckle, he'll explain how it's really one of the rooms set aside for staff. For a small amount, he'll arrange to have the player character in question stay in a suite that's normally reserved for big name politicians or movie stars. "You really won't want to stay in that room", he'll say in complete sincerity.

*** Till the Ball

Players now have a bit of freedom to wander around the hotel, relax, read that dusty old tome they've been carting around for a few adventures, or perhaps go grab a bite to eat. It should be noted that the plaza and streets outside are now collecting a lot of water and the doorman will discourage anyone going out. Shop keepers are closing early and the streets are more or less deserted. Investigators may dash off to a general store across the plaza to buy any last-minute items; however, they will be met with a store keeper about to close the shop and will not abide any browsing. Players unable to directly state what they need will need to pass a *Fast Talk* check to look around. The store keeper wants to get home as soon as possible and will get increasingly impatient for investigators dilly-dallying.

The Rainyday Ball begins at 8 o'clock and is the next major event to proceed the storyline. There are a few items of interest and events below that can be sought or happened upon. Events are in a non-specific order.

*** Exploring the Hotel

Investigators exploring the hotel without a map might get a little off track, any bellhop or waitstaff will direct investigators and mention a map is available at the front counter.

*A Bite to Eat:* Food is located at the dining hall serving common breakfast in the morning, and soup and sandwiches lunch. All for a modest sum. Inquiring about dinner, waitstaff will inform investigators that it's served in the ballroom, and apparently they have something special going on tonight.

*A Drink:* The bar is open and serving drinks, though as this is prohibition, an obtuse way of asking for alcohol is needed. The bartender is rather short-spoken and will direct any questions about history or people to Ernesto.

*The library and gamesroom:* The library is a modest collection of books and magazines. Mostly common thrillers, penny-dreadfuls, and fashion mags, there is some books about local history that might be useful for reference to other adventures. Investigators can search the stacks with a *Library Use* roll, but even with a success will find no Mythos or Occult books unless the Keeper wishes. The games room contains a single billard table and a few card tables. Cards, boardgames, and billard balls and cues are stored in a tall cabinet in the corner.

*Pool and garden:* Both the pool and garden are of little interest for investigators. The pool is unused and overflowing. The garden, once containing lively flowers and vegetables, is now slowly dying from the torrent of saltwater.

*** Hotel Happenings

*An odd thing to wash away:* Investigators watching the rain come down outside may be asked to make a *Spot Hidden* roll. Those succeeding will see a fish among some of the refuse being washed away costing 0/1 SAN. Any investigator seeing this can make a Hard *Biology* roll, with a success recognizing it as a saltwater fish.

*Meeting Ernesto:* Ernesto wanders the halls seemingly lost, though he will ask that directly to any investigator not on a direct course. Those engaging Ernesto in conversation will be treated an archives worth of facts and anecdotes about the hotel and previous patrons. See the NPC section for more information on Ernesto. Investigators may coax some interesting information from Ernesto concerning guests at the hotel, as Ernesto knows a little bit of information about everyone staying or working at the hotel (perhaps he even knows a little bit about investigators even, see his character profile about Mythos awareness).

*The Ball Announced:* Sometime midday, a sign will be placed outside the Ballroom annoucing the Ball at 8o'clock. Bellhops, managers, and waitstaff will mention it to passing investigators as well.

*Relax:* Investigators wishing to just simply relax may take up a game of cards, read a book (of the non-sanity-reducing kind), or take a snooze. Kindly keepers may award a point of SAN.

*The Basement Leak:* At any point during the first day Mr. Fines and presumably a handyman will be seen rushing down the hall towards the basement storage, players making a *Listen* roll can only make out "Leak", "that basement is old", and "Why didn't you tell me this sooner?". Anyone following the duo will need to make a *Sneak* roll or will be noticed by Mr. Fines who will tell the handyman that they'll discuss this later and walk off to their normal duties. If asked directly about it, Mr. Fines will tell investigators not to worry and will answer no further questions on the matter. Investigators with access to the basement storage will see the basement storage is now flooded with several inches of water.

*Searching for Sleep:* Investigators around the lobby will see Peter King insisting on getting some sleeping aid, as a light sleeper he feels he won't be able to sleep through the storm. The hotel doesn't have any sleeping aids on hand, but Mr. King will insist. If it's early in the day the hotel will fetch staff to go purchase it from a local store. If it's later in the afternoon the hotel will be reluctant to send someone out when it's obviously flooding. An investigator can volunteer here and Mr. King will give the investigator 5$ to purchase "Missus Timmons Quality Sleeping Draught" and to keep the change (it costs 1$). Investigators taking up this task will need to venture out. See the section on Venturing Out for more details. King will wait in the lobby for an hour then go to his room feeling cheated. He'll leave a note at the lobby for the returning investigator directing him to his room. Sincere gratitude is rewarded if the sleeping aid is delivered.

*Lights Flicker:* Lights will randomly flicker or drop then come back. Anyone within earshot of an electric gramaphone will hear the music briefly slow down then speed back up. Investigators with phobias to certain auditory stimulae may need to make a SAN roll (0/1D2).

**** TODO Peter Kings room #

*** Venturing Out

Investigators might try to leave after they've settled in. Unfortunately the rain has only gotten worse and the streets are visibly flooding. If the doors have not yet been locked (see the next section), otherwise they're free to go. The streets are difficult to traverse and navigate in the storm, if investigators did not ask where a certain shop could be found: a successful *Navigate* roll will be needed to locate it. Such as the drugstore, if they've been tasked by Peter King. A general store, which sells guns and ammunition will need to be asked about or found as well. A successful *Luck* roll will be needed to see if any store is open otherwise they've closed once the flooding began. The drugstore has the exact sleeping aid Mr. King has asked for. This will be the last opportunity to purchase something in a store until the flooding gets too bad.

*** Refuges from the storm

Investigators hanging out in the main lobby will see a group of four or six people enter in the main entrance. They look to be homeless, but it's hard to tell since being soaked head-to-toe might give that impression. The doorman will stop them from going any further than a few steps and ask the group to leave. What starts as a sorrowful plea, as no other place was open to seek refuge, to a full on violent altercation between the doorman and the group. As soon as it starts another doorman across the hall and two bellhops, one being Charles, will step in to break up the fist fight. Investigators helping to break up the fight will get caught in the fight too. After a few combat rounds the fight will end with Mr. Fines yelling at everyone to stop at once and for the group to leave. His right arm is inside his jacket pocket, at *Spot Hidden* roll will tell it's a gun. The group reluctantly leave, but not without spitting on the ground as they walk out into the pouring rain. After the group has left and the commotion has died down, Mr. Fines relaxes and approaches the doorman, now nursing a bloody-lip. Investigators that make a *Listen* roll will hear Fines instructing the doorman to lock the doors. At this point all entrances to the outside street are now locked, with any of the doormen and Mr. Fines having keys. No one is trapped inside though, anyone asking nicely will be let out.

*RUFFIANS*
| STR | CON | SIZ | DEX | INT | APP | POW | HP |
|  40 |  65 |  65 |  55 |  45 |  50 |  45 | 8  |
*Build:* 1
*Move:* 7
Fighting (Brawl) 35%
Dodge 25%
*Skills:* Intimidate 40%

*** Rainyday ball

Any NPC of note in this scenario will attend, including Ms. Davos, finally awakening from her day-long rest. The ball will take place at the hotel's grand ball room. Dinner is served and a popular jazz band is playing. As investigators arrive they will be seated together at a table close to the band. Though lighting will storm outside and the lights will flicker momentarily throughout the event: the band will play on. Dinner consists of a choice of steak or fish with flan for dessert. Investigators are encouraged to get up and dance, the music is great and lively. Investigators brave enough to dance will have fun and recover 1 point of SAN.

*Listening in:* Various conversations can be eavesdropped on, though it might be difficult to tell who said what to whom. This will also depend on where the investigator is in the room though Keepers can pretend all the conversation is around them and make it audible from their table. All the investigators can each make a *Listen* roll. Read aloud one of the following snippets of conversation for a normal success, a hard or extreme success will reveal exactly who said it:
- "I've been watching it outside, the city is flooded..." - Random guest
- "Check out the red-head by the bar over there!" - Random guest (location anywhere)
- "I been having just the worst of luck these days" - Miriam, whining to a sympathetic ear
- "Let me tell you about the future of communication, hell I can even contact the dead with the power of scientific method!" - Mr. Hickenthorpe, schmoozing around the bar area
- "I tell you, I saw a fish wash down the street!" - Random guest
- "That man is an idiot and a charlatan" - Random guest pointing at Hickenthorpe
- "They say the rain brings the dead closer to our world" - Ernesto spooking a random couple
- "Oil is never going to lose its value, it'll only go up" - Ronald Pierce by the bar
- Keepers are free to add their own.

Ms. Davos will be drinking by the bar, completely engrossed in her own thoughts and conscious. If questioned she will just mumble some quick dismissal. If she continuously pestered, she will snap out of it briefly and tell whomever to buzz-off. The bartender will intervene afterwards.

Hickenthorpe will gladly talk the ear off of any investigator over his revolutionary invention, especially if he notices, or an investigator ventures, any wealth status. He states his intention to demonstrate his invention tomorrow afternoon as he intends to setup a small 'demonstration' in the parlor. If *Persuaded* or bribed (to the tune of 20$ to show commitment) he will give the investigator a private demonstration tomorrow morning in his room, and gives out his room number. A hard or better success on the *Persuasion* roll might convince him to show it privately after the ball, but if the investigator is a woman he'll certainly take this the wrong way.

Peter King will be quietly eating by himself.

Ernesto is wandering around the room telling ghost stories and generally being charming.

Mr. Fines is going through insurance paperwork as he knows the flooding will cause significant damage.

Lillian is playing cards by herself in the gamesroom. Ronald is chatting with some businessmen by the bar.

*The lights go out:* As the night go on, and after all the investigators have picked up all or most of the clues given out: the poor overworked power mechanism will finally give out and plunge the room into almost complete darkness. Frightened gasps and cries will be let out, the band stops abruptly. A pause stretches out in the room as people wait to see if the power will kick back on. It does not. Some minor panic will sweep the room as people trip and knock into things. A few minutes later several hotel staff will enter the room carrying candle lamps. Mr. Fines will materialize onto the stage as he lights a lamp, he will try to calm the guests down and inform them that the staff will carefully take them back to their rooms, and to please be patient as they do so. Most of the panic will die down at this point. Staff carrying lamps will go from table to table to escort them back to their room. If the investigators are seated together, they'll be guided back soon after.

*The trip back:* Investigators will notice the first floor carpet is wet, water can be heard dripping in places unseen throughout the hotel. If an investigator looks outside they will see the streets completely flooded past the doors to shops and coming up to the windows. The hotel is raised off the ground a bit so the water has only reached the door. Of the staff that returns player character back to their room, one is Charles and he has quite a grim expression on his face. If questioned about the situation he'll lie and tell the investigator that everything is alright. A *Psychology* roll can easily tell that he's lying. If pressed he'll reveal that the basement is flooded and the rain isn't letting up. He'll try to explain how grim the situation is getting, that the staff are considering fleeing home at night. He won't be much help if the investigators want to escape the hotel. It's one of the few tall buildings in this town and he'll sincerely advise the investigator to stay here. By the time he sets out to find his home, it'll already be underwater.

*** That night

After returning to their rooms, they're left with a few candles on their dresser. Investigators can attempt to sleep, but it won't be a very restful one. In addition, a couple of major events happen during the night.

*Lillian and Ronald:* As the lights went out, Lillian finds herself in complete darkness alone. She'll begin to call out. Ronald, a little inebriated from his time at the bar, has been expecting Lillian to be in his room (they're sharing a room), when he finds it empty after being escorted back, he'll start hollering out. Investigators easily hear this from their rooms, if they go outside Ronald will quickly enlist them to help find her. He has no idea where she is, and his current state doesn't help matters. After stumbling a few times, he'll sit down and beg for investigators to find her between blubbering on about how horrible a father he is. Lillian is stumbling around the gamesroom, eventually making her way out and wandering down the hall. She's in tears of fright at this point and her call is quite weak. Investigators might only have their candles to help them navigate. Lillian will try to find her way back to her room but get lost and roam the first floor blindly. Keeper should mark and track where Lillian is as she wanders around. After reaching the first floor, investigators would be wise to keep quiet as they might hear a faint '...dad?...' in the air. As water is dripping down, the Keeper might impose a group luck roll with a failure resulting in a candle spluttering out. If Lillian is found she is crying and soaked, she's grateful for the assistance and wants to get back to her room. After being guided back her father waits slumped down outside their room, they'll embrace in tears and be very thankful. Ronald will give investigators his business card and ask them to call upon him anytime. He won't remember any of this the next morning. If Lillian is not found after an hour or investigators refuse to help, Ronald will attempt to find her on his own which results in him tripping and falling on the stairs. He's unconscious when the waters consume his body. Lillian at least fairs better as she eventually makes her way back to her room, only to find no one there.
It should be noted here that there is no existential threat here beyond the darkness and flooding, unless the Keeper wishes otherwise. Attempts should be made to keep the tension high and filled with uncertainty.
If investigators were successful in saving Lillian and reuniting her with her father, they are rewarded with 2 SAN points each.

*Flooded:* At around 1am the entire first floor is foot-deep in water.

*The Staff Flees:* Around 2am, the majority of the staff enacts a plan to flee to their homes. They set off, waist deep in water with suitcases filled a few belongings, some pilfered, and attempt to reach their home. Those that leave are never seen again.

*Poor Peter King:* Even if investigators never aided Peter King he managed to find some sleeping aid (a conversation struck up during dinner was rewarded when his conversation companion offered some). He takes too much and at around 4am is unable to wake up as the waters rise above him.

*Bad Dreams:* If/when investigators finally lay down to sleep, they will not have pleasant dreams. Read the following aloud:

/You find yourself flying over the sea, or what appears to be the sea. The unmistakable smell of brine fills your senses. Morning light seems to come from all directions. You have no control over your direction, being guided by some unknown force. Your attention is to the water: gray and calm, and you are almost close enough to reach out and feel your hand gliding through the water. Just below the water's murky surface, you can see structures. The are ancient, sunken, and long forgotten. You find yourself in a sort of vast forest-like clearing, with an endless wall of fog stretching out and enclosing the sea. The wind picks up and with it your thoughts on this being a clearing change to something more akin to the eye of the storm. You are moving faster now and the water beings to sway and swell as turbulence distorts it. You feel the brine in your eyes, on your skin, and dampening your hair. The light begins to fade to darkness. You wonder what you are being guided to, but that becomes painfully clear as you finally see what has been there all along. A great tower of water reaches up into the sky. It is as if a great waterfall began from heaven itself and crashes down here. You are moving towards it and no amount of willpower will stray you from this path./

The next part depends on the behavior of the investigators. If investigators helped out Lillian and Ronald, read the following:

/The light has ceased and only a dim pale moonlight keeps this reality from crumbling. You can feel it now. Some ancient evil is waiting for you in that tower. The clap of thunder jolts you. A flash of light floods all corners, revealing what should have laid hidden under darkness. It was only for a second, but you saw it. A great silhouette within the tower. A wing'ed giant with tendrils for a mouth. The Great One beckons you. You feel yourself being pulled into the tower just as your body, your real body, tries in vain to awaken you. Terror seeks to wrack your body, but instead you are filled with determination to stop this evil. You cannot let this evil awaken into our world. You do not know how, but you are the only one that can stop it. A woman. A book. Mercifully, you are jolted awake as the water of the hideous tower envelopes you./

If investigators failed to aid Ronald and Lillian, read the following instead:

/The light has ceased and only a dim pale moonlight keeps this reality from crumbling. You can feel it now. Some ancient terror is waiting for you in that tower. The clap of thunder jolts you. A flash of light floods all corners, revealing what should have laid hidden under darkness. It was only for a second, but you saw it. Only a glimpse was enough to freeze what little free will you had. A dark mass fills the tower, tendrils seem to tickle the walls of water. The horror beckons you. You feel yourself being pulled into the tower just as your body, your real body, tries in vain to awaken you. Terror wracks your body and saps your strength as you start to sob. You feel judgment upon you as you blubber and bluster every crime and sin you've committed in your life. You wish for pity, but feel something much worse: indifference. No one cares and what little importance you have in life is that of food and sacrifice. The tower is close. You panic and try to squirm and squeeze away, but it is for naught. You are doomed. Mercifully, you are jolted awake as the water of the hideous tower envelopes you./

If the party received the second (bad) outcome, each investigator will need to make a *Sanity* roll (1/1D4). With that, the first day has ended and Act 2 begins.

** ACT 2 WATERS RISING

*** Rising Waters

The water hasn't stopped, what was initially thought to be an unfortunate flash flood has now turned into something biblical. Refer to Map 2 for all the areas underwater, which includes most of the first floor. Deep Ones will start to appear and start attacking investigators. In addition, refer to optional hypothermia rules if needed.
**** TODO Add maps

*** Awakened into Chaos

Investigators who managed to find sleep will be awakened around 7am with yelling and screaming coming from outside their room. Power has still not been restored but the day is rather bright despite this and although it doesn't seem to be raining as hard as it was, there is still a steady downfall. Anyone looking outside will see a city looking more like the canals of Venice than the quaint town people remember. Investigators making a *Spot Hidden* roll will see some fish-sized dark shapes moving in the water (SAN 0/1). It smells deeply of the ocean, but tinged with a stagnant aroma.
As investigators get their bearings, they will again hear the roar of the crowd outside. Going out will find a group of haggard looking guests, some still in their party gowns, standing around and yelling at the sole staff member. It's Charles, the bellhop who helped the investigators before, he chickened out on the plan to flee the hotel with his fellow staff members after seeing how high the waters had gotten. The guests are battering him with questions about where everyone is, when help is going to arrive, if they'll get a refund on their stay, etc. Charles is doing his best, but is getting visible stressed out. Investigators can help in getting the guests off him or they can add to the battery: he really doesn't know anything. Ernesto, Fines, and the rest of the staff are missing; he hasn't had access to a radio to know if help is coming; sure you can have a refund, whatever.

After all the pointless questions are exhausted the topic of what to do might be presented. Charles will ask investigators to go check on the other guests and see if they need anything. If the party has gotten on Charles' good side, either by defending him or helping out showing the party can be trusted, he might help further by offering keys/navigational help, etc.
As he leaves to go find a closet to hide in, he'll turn to the investigators and say, "After you've checked in on the guests, find that inventor fellow, Hickenthorpe, said he had some sort of communication device. See if he can call for help with it". He won't know where he's staying exactly, but he believes he's on the third floor.

*** Checking in on the guests

Investigators can attempt to check on the other guests as mentioned by Charles. Most doors will not answer, or tell whomever is out there to leave them alone. A few might open the door and talk to the investigators: some will just be sick with worry, others will be hungry or thirsty (the kitchen is deep underwater and the rain is briny and undrinkable). Lillian and Ronald are in surprisingly good spirits as they play cards and converse, in all the busy life Ronald has lead he's had very little time to actually talk to his daughter. If investigators might suggest they move to higher ground, Ronald (and a few other rational guests) will agree and start to pack their things to move higher up.

*** Ernesto

Like a ghost, Ernesto will appear wandering down the hall. He is distraught and near catatonic, mumbling about his hotel being ruined. If approached he'll grab a hold of an investigator and ramble on about 'How many ghosts can this hotel take?', 'This storm isn't ordinary, the work of great evil it is', 'That woman, Davos, she has a dark energy about her'. If investigators are gentle to poor Ernesto, he'll calm down enough to respond to basic queries. He'll invite investigators into his permanent suite he lives in and even offer some tea (his pitcher of water is likely the last gallon of fresh water in the building). He believes the storm is supernatural and Ms. Davos is the cause of it. He is correct on both counts, yet he knows not where she is staying (only Fines would know that).

*** Deep Ones Appear

By noon the waters will have risen to the top of the first floor stairs. It'll probably be time to find Hickenthorpe as well. Investigators approaching the main stairway to head up will see the water level has reached the stairs leading down. The water is brown and murky, but the object of immediate attention will be large pale body floating just below the water (SAN 1/2). This is Peter King, after having drowned in the night his corpse has been floating upwards. Ask for a *Spot Hidden* roll afterwards, pass or fail, they notice the corpse move slightly. Then in a few seconds or so the corpse is dragged down into the water. If they made the previous roll say it looked like it was grabbed and pulled under, otherwise it looked like it finally sunk below the water.
The water is now home to a couple of Deep Ones, human-sized fish monsters and the servants of Cthulhu. Anyone swimming or wading into the water at this moment has a chance to catch the attention of a nearby Deep One. See rules on Deep One Encounters under Keeper Information for more details.
The Keeper can have a Deep One emerge and attack here, as it sensed the nearby investigators, as would previously failed 'Pushed' rolls. Deep Ones can't stay out of water for long but it will wander the halls and look for anyone nearby (such as guest trying to head to the third floor).

*** Hickenthorpe

After receiving the tip about Hickenthorpe, investigators might slowly make their way there. He's hiding in Room TBA. He, like almost every other human inhabitant of this building, is scared and completely unsure. All pretense of a smooth-talking conman has fled, replaced by cowardice and fear. Unless a previous arrangement was made he'll be reluctant to answer the door, even so far as bluffing he has a pistol and is willing to use it. *Persuading* Hickenthorpe won't be much of a challenge though, he'll open up for any (false or not) promise of help and rescue. Those wishing to *Intimidate* him with a threat of being left behind will similarly work. Failing that, his door is visibly flimsy (as are most doors on the top floor) and can be broken down with a *STR* test. Similarly if a deep one is in hot pursuit of investigators, cries of monsters will only send Hickenthorpe hiding instead of opening the door.
Hickenthorpe is hiding behind the bed, he carries no weapon on him except for an empty bottle of whiskey in reach. If feeling threaten for his life or a Deep One fallows investigators in, he'll throw the bottle at the nearest perceived danger and try to flee. If not caught he'll flee to the lower levels where he'll be at risk of deep ones dragging him under.
Once things have calmed, Hickenthorpe will being speaking to investigators. Most of what he says will be tearful blubber. If asked about his revolutionary device, he'll seem a bit surprised and taken aback. He's forgotten about the con game, only wishing to be back home and safe. He'll show the investigators his device, perhaps in the back of his mind his device actually does work and maybe these strangers will know how to end this nightmare.
The device is contained in a locked briefcase in his closet. He'll retrieve it, open it, and present it to investigators, answering any questions they have. The device looks like a small portable radio torn inside-out, with wires, magnets, and small pieces of metal hobbled, tied, and glued together, seemingly at random. Have every investigator viewing the device make an *INT* roll, succeeding reveals what should be obvious baloney. While not right out admitting an obvious con, he'll explain he read some books on radio technology and was way in over his head when he created the device, and who was he to argue if people gave him money?
The device being a dead end, investigators might inquire about other avenues. Hickenthorpe won't know much of anything directly related to the ritual, but if asked who might Hickenthorpe will point them toward Ernesto. If asked about anything unusual, Hickenthorpe will offer up that he heard some strange sounds the other night, after everyone had gone to sleep. The night before the investigators arrived. He's referring to Ms. Davos as she went through with the ritual. She is only a few rooms away, and waits there now.

**** TODO add room #
*** Tracking down Ernesto

Ernesto is standing out on one of the terraces, observing the apocalypse as it unfolds. Finding Ernesto requires searching around while Deep Ones are on the look out. If passing through a hallway with a window outside, a *Spot Hidden* or *Luck* roll might be granted to catch someone standing out on a terrace. Joining Ernesto, investigators will see the true destruction the ritual has wrought the city. The scene is not unlike the /Wanderer above the Sea of Fog/, only rooftops are visible now and a massive perimeter of fog around the city seemingly transports the view to another dimension. The rain is gone but for a light misting. Now dusk, the colors have warped and shaded this land into an alien plane though that's not what draws the attention at first glance. Situated not far from this terrace lies a massive column of falling water. Investigators will recall back to their dreams at the end of the first day and seeing this carries a great penalty to an investigator's sanity (1D4/1D8). Investigators failing the test will feel an ominous presence growing within the column of water.
Ernesto will tell them he knows who did this, as he felt the shadow of mythos behind her eyes. He is of course talking about Ms. Davos and will tell investigators exactly which room she resides in. If asked for any advice on how to end this, he will point to the column and say, "If she cannot help you, you must confront that." He'll also point out the general direction of a military fort on a hill nearby, which can be made out if a *Spot Hidden* roll is made.
Ernesto can be a source of *Cthulhu Mythos*, as he has encountered it in his long storied past. If asked about it, he can related a story about how he once lived in a convent in Mexico that later turned out to be a temple of cultists. He was attacked by a living shadow but managed to escape and eventually found himself in America. Listening to this will increase investigator's Cthulhu Mythos skill by 1D3.

*** Wandering About

Investigators who have failed to divine the clues leading to Ms. Davos, might become stuck at this point. Between the morning and now, things have gotten much worse in the hotel. All the walls seem to be dripping with brine, blood smears the hallways floors where it appears someone was dragged from their room into the murky waters filling up the second floor stairwell. Crying can be heard somewhere in the distance. Charles, Alfred, Ronald, and Lillian have all disappeared. Worst of all, it is getting dark and electrical lighting has long ceased. Deeps ones will be much more active at night and will attempt to break down doors if they sense there is prey on the other side. Once the realization of total darkness has set in, a plan might be formed to find some flashlights. If investigators currently posses flashlights and lanterns, it would be a reasonable assumption they would have gotten wet and become non-functioning. There is one utility closet each of the second and third floors of the hotel, the first one is completely completely submerged, and the second is on the third floor. Miraculously it's unlocked and has been mostly untouched, inside contains two flashlights, two packs of a dozen batteries, some linen, and a few random cleaning products, and a large friendly bottle of rat poison. The flashlights require two batteries each. The batteries are the cheap paper kind and will quickly cease to function if they get wet. What the investigators do with the rat poison is entirely up to them. It would probably take a lot of rat poison to kill a Deep One.
As investigators are raiding the utility closet, Ms. Davos will briefly open the door of her room to begin to paint an Elder Sign on her door, caring about or noticing nothing else. Investigators standing watch can easily catch sight of this as it's only a few doors down. A *Listen* roll will also alert them as she opens and closes the door, if no one is looking around.

*** Ms. Davos

This is the crucial point in the investigation, as Ms. Davos posses the only means to stop the calling of Cthulhu and possibly bring things back from the brink. She's been waiting here, since the beginning, except for a stroll out to the rainy-day ball. She's currently tired, high-strung, and mentally deteriorating.

As explained in the *Wandering About* section: if the sun has gone down, an Elder Sign has been crudely painted on the door. It was painted using a mixture of hotel courtesy ink from an inkwell and her own blood.
If investigators knock on her door, a reflexive response of, "Who is it?" will be given. Investigators are on their own from here, as Ms. Davos will not open door unless a good reason is given. She knows an Elder Sign will protect her from Deep Ones (though it's not as effective as she believes), so she's only putting herself in danger by opening the door. If asked, about the flood and Deep Ones, she will flatly state that there is nothing that can be done. A *Persuade* roll can be attempted with a valid persuasive argument that they are probably the only ones that can help. She will let investigators in regardless of rolls if they let on their familiarity of the mythos or speak about the dream they had. She will start to get annoyed however if investigators try to deceive her about their intentions as she is no idiot.

Inside the room is a wreck: the bed has been overturned, sheets and pillows are strewn about, the floor is stained with trails of blood, and a large arcane symbol has been carefully scratched onto the floor. Ms. Davos will spill it all at the point, her relationship with the Yanguana Society, the book, the ritual, and her conviction that it can be used to help the world, how she checked into the nicest hotel she could find and went forward with the ritual. If asked about the loss of life, she'll make a quick offhand comment about the world not needing anymore people before stating that she knows, and is sorry. The conversation with Ms. Davos can go many ways, she is willing to explain how the spell can be, and should have been, used in completely arid places in the world to bring a bounty of water and life. If pushed on the guilt about the loss of life, a successful *Persuade* roll can be made against Ms. Davos. On a tie or success, she will break down and start sobbing, fully comprehending what she has done.

She genuinely believes there is nothing that can be done, but if asked about the ritual she'll show investigators the book. Investigators can all make *INT*, or *Cthulhu Mythos* rolls (perhaps even a group *Idea* roll if players get wildly offtrack). Making a Cthulhu Mythos roll will lead them to believing it can be reversed using the same ritual, otherwise a skill roll success will lead investigators to believe that studying the book might uncover some clues. With that, a case can be made to lend the book out for further study and Ms. Davos will reluctantly agree. In her mind, the damage (and supposed benefit) has already been done and while she doesn't want to be violently killed, she has since resolved she won't live past another day or two, so what does it matter to her? She will let the book go and will only wish to be left alone again. Her last request is to close the door on the way out. She won't speak or aid the investigators any time soon.

If the door is forced open, she is threatened or attacked, she will defend herself against investigators with her knowledge of deadly spells. She is protective of her book, and won't stop attacking if investigators take it against her will. Her attacks will stop if investigators get ahold of the book and threaten to destroy it however.

*JULIA DAVOS*, /former Yanaguana Society Member/
| STR | CON | SIZ | DEX | INT | APP | POW | HP |
|  40 |  65 |  55 |  75 |  85 |  70 |  80 | 16 |
*Build:* 1
*Move:* 8
*Magic Points:* 20
Fighting (Brawl) 25%
Dodge 25%
*Skills:* Appraise 60%, Charm 55%, Cthulhu Mythos 30%, History 50%, Intimidate 40%, Library Use 65%, Listen 45%, Occult 70%, Languages: (French) 40%, (German) 35%, (Latin) 75%, Persuade 55%, Psychology 40%, Spot Hidden 45%
*Spells:* Breath of the Deep, Dominate, Elder Sign, Mindblast

*** The Book

See Keeper Information about the /Canticum de Abyssi/, but needless to say there /is/ a way to stop the ritual but it will take the rest of the night of studying the book (1D6+1 hours). Successfully passing the skill checks will impart the information of stopping the ritual, by means of slight changes to the pictograph and changes to the utterances of the words. Attempting this corrected ritual will take more time (1D3 hours). Investigators failing their sanity rolls and believing in the benefit of the ritual can still help their comrades in stopping the ritual. Assuming a long shot happens and they survive, then perhaps this investigator might just repeat this experiment at a future time.

See /Call of Cthulhu: Keeper Rulebook/ on rules for /Dismiss Deity/. The dismiss spell can be cast as soon as it is learnt; however, sensing dismissal Cthulhu will attempt to send hoards of Deep Ones to try and stop the Investigators. See below *Stopping the Ritual* for details.

**** TODO create an actual dismiss spell since it differs from the rulebook

*** Deep Ones on the Hunt

Deep ones will patrol around the water and hallways. The Keeper should note down two or more general locations of Deep Ones as their patrol area. Anyone wandering the halls, going outside, swimming or wading in the water will need to pass a *Stealth* roll or attract the attention of the nearest Deep Ones. Similarly, Investigators can attempt to make a *Listen* roll for Deep Ones.

Deep Ones may attempt to capture humans and drag them under the water, with the goal of bringing them to the tower of water as sacrifices. Deep Ones are fast swimmers but being dragged through the water will require a *Swimming* or *CON* roll to keep from drowning. See the section of fighting maneuvers in the /Call of Cthulhu: Keeper Rulebook/ to free oneself from a Deep One's hold. Those that survive the drowning won't have much cause for celebration as they'll be pulled up into the torrent of water and consumed by the increasingly material form of Cthulhu. Allow for a last ditch effort to escape, a hard *Luck* roll will be required to grasp a building edifice or large piece of debris, they can then pull themselves free of the water torrent. Unfortunately, they will find themselves close to a Great Old One, though not yet in full control of its capabilities, half a mile away from the hotel, and near the source of all the Deep Ones. Truly a pickle of a predicament!

*** A Cry for Help

In the middle of the night, perhaps while one investigator is studying the book: a faint cry is heard through the pipe works that connects the heating to each room. This person is a woman named Miriam Pell and she is very unlikely to survive. Miriam is trapped in an elevator shaft beneath the elevator, currently stuck on the third floor, and, since the loss of power, has ceased from operating. The hotel's heating and water pipes snake through the elevator shaft and it's through this her calls are heard. Sleeping will be a bit difficult as the periodic sounds will be heard throughout the night, especially right when they think sleep has finally caught up with them. Investigators must make a *POW* check to essentially ignore the cries and get to sleep. Failure will result in a Sanity check (1/1D3), as their inability to sleep along with the cries deepens their level of stress.

If investigators wish, and at great peril, they might try and launch a rescue operation. The first task being discovering the whereabouts of this poor person. A *Listen* roll is required to determine the sounds are coming through the pipes. Speaking at or into the pipes will have little effect. If investigators listen intently to the pipes: call for another *Listen* roll, eventually after bemoaning some other unimportant troubles, Miriam will mention they're in some sort of elevator shaft. If investigators make their way to the elevator, they'll find no access under the floor. Unless they have access to welding equipment, they will have to come up from the second floor. The second floor which is almost completely submerged at this point. Investigators will have to swim, mostly submerged on the second floor to get to the elevator doors there. There is about a foot or two to breath towards the ceiling. The elevator doors can be pried open with a tool like a crowbar or fireman's ace and give little resistance, otherwise a successful *STR* or *DEX* roll is required to pry it open with one's fingers. Opening the shaft will release some of the water and drop the rescue down to the second floor level. They will be frightened and panicked, but if held firmly and carried along they can make it. A *Swim* skill roll followed by a *CON* roll is required to carry anyone to safety. Failing these rolls might cause Miriam to slip away or get caught on some obstacle.

The hazards of this operation are numerous:
    - Three deep ones patrol the waters of the hotel, via land and water (see the section on Deep One patrols).
    - At this time of day almost all light is extinguished making navigating very difficult.
    - Obstacles in the water: chairs, tables, perhaps corpses have a chance to snag an investigator's foot.
    - An investigator will need to keep their head above water in an enclosed space.
      
It is up to the keeper's discretion on how to apply these obstacles, but it can quickly make a rescue operation a statistical impossibility. Bringing Miriam back to the (tenuous) safety of the third floor has its rewards however. A profuse thanks will be given, including a tearful speech on how, just perhaps, the human race isn't doomed and worth fighting for. All investigators who helped in the rescue, even in a small way, are rewarded 1D8 Sanity points. Keepers may also give out a bonus die for all Sanity checks on the third day, as the investigators are filled hope and determination to see this to the end.
    
Investigators need not stick their necks out however. At sometime around dawn of the third day, the elevator shaft will be flooded up to the elevator itself. Anyone still remaining in the shaft will have no escape or be left with any air to breathe. If investigators failed to rescue Miriam, they are doomed. She will use the last of their breath to scream out for help, then cease. It's the ceasing, after such a long and protracted death that really hits the investigators the hardest. Hearing this will result in a Sanity check (2/1D6) with failure resulting in a feeling of bleak inevitable doom for the Investigators.
    
With that, the final day arrives...

** ACT 3 THE CALLING

*** Rising Waters

The hotel at this point is completely flooded three-quarters up the second floor, where only the third floor promises any dry land to speak of. The rain itself has stopped for the most part, replaced by a giant unearthly column of water where Cthulhu awaits. The valley has been mostly completely covered by water at this point, only the tops of large buildings, those fortunate enough to be on the higher outskirts of the Valley, and the towers of the old fort, remain above water. Trash and debris, even a few floating bodies bob up and down on the mildly turbulent water.

**** TODO add a map

*** Stopping the Ritual

The final day is perhaps the most perilous and yet promises the most freedom. All other distractions are gone safe for Cthulhu and its minions. At this stage, there is no hope for this city to return back to normal. Most inhabitants that did not escape, late in the night on the first day, have drowned. Deep Ones hunt down anyone they can find, usually those trying to stand out in hope of rescue. Those that remain are holed away in closets or rooms, starved and dehydrated.

Cthulhu itself has partially materialized inside the great column of water some 200 feet above the waterline. Psychically commanding the Deep Ones to capture humans, Cthulhu consumes the sacrifices brought to it by sucking them up into the column, then absorbed into its half-materialized psychic form, killing instantly.

While the town cannot be saved, perhaps the investigators, the remaining survivors, and the land itself can. Cthulhu will leave this plane of existence by the following means:
- Letting Cthulhu devour enough humans for it to be fully materialized and satisfied, whereupon it will then, in a span of a few minutes, teleport itself and a mile-wide radius of the sunken town deep below the ocean. Anything still alive will instantly drown under the water pressure. It is theorized that this is how, centuries before, the great underwater cities of Mythos lore were born.
- The ritual of summoning is stopped by casting the dismiss spell. See the *The Book* section above for details on casting the spell.
- Cthulhu has sustained enough damage to undo its materialization. See the next section for details.

Casting the spell requires somewhat of a dry place, one of the empty hotel rooms would suffice. Once the dismiss spell has begun, Cthulhu will likely know this and send Deep One minions to stop the investigators.

*** The Final Battle

If the ritual cannot be stopped with magic, it /can/ be stopped via physical means. As Cthulhu has not fully materialized it is substantially weaker to its full form. This form has half HP, no armor, and cannot attack directly, but don't believe this will be an easy task for investigators. Cthulhu can call a limitless supply of Deep Ones to attack investigators and can cast a number a deadly and horrifying spells.

Before it fully materializes, investigators are mercifully spared the direct sight of the Great Old One, however seeing this entity will still take a great toll: a living silhouette in the shape of Cthulhu, with crackling green energy dancing all about it. Seeing even a glimpse of this shadow will cause a Sanity check (1D4/1D10).

From the hotel, it is unlikely, the investigators will have any means to hurting Cthulhu. They will have much greater success from the military fort but requires them venturing out, swimming and climbing from rooftop to rooftop to get to the only place close enough and with the needed artillery to send Cthulhu back. Upon venturing out, the Keeper should describe the what is left of the town and any remaining buildings, including the military fort.

See the map for the military fort, it lies some 200 yards away from the column of water. On the second floor there contains an armory with rifles and ammo needed to shoot Cthulhu and on the nearest tower of the fort contains a machine gun.

Landing a shot against Cthulhu won't be easy, at that range it will require a Hard success with the appropriate rifle or machine gun. In addition the water acts as a sort of armor, slowing the bullets down and reducing damage.

As soon as the first bullet lands successfully, Cthulhu will summon its hordes of Deep Ones at the Investigators. Every 1D6+3 rounds, another Deep One emerges from the water and tries to kill or capture an Investigator.

As soon as Cthulhu's HP have been reduced to zero or lower, it will vanish with a loud terrifying cry. All Deep Ones still alive will immediately dive into water upon hearing this. Lastly, the great column of water will finally cease and crash down.

Any NPCs rescued or befriended can help out here: Ronald is happy to help take up a rifle, Ernesto, Charles, Miriam, and even Ms. Davos can help keep Deep Ones at bay.

When all seems lost, perhaps when investigators are on the cusp of death by Deep Ones or insanity, should Cthulhu fully materialize. The torrent of water will drop and full sight of the Great Old One will be beheld (1D10/1D100). Wasting no time, it will hold aloft a hand and send the entire vestige of the town and a near sea of water with it.

**** TODO add Shadow Cthulhu stats, should also have a map of the fort

** AFTERMATH

*** All is Lost

Investigators who've failed to stop the ritual will be dragged back with all the town, creatures, and every drop of water down to the bottom of the ocean from where they came. What need of the town to this ancient creature is unknowable. It could be theorized that all great sunken empires were born of this means. Cthulhu will not stay, for the stars are not right and it was not truly time for the Great One to awaken. This need not be the complete death of the party, perhaps they will awaken in R'lyeh. Partially mended but forever broken in other ways, and completely and utterly lost...

*** The Ritual Abates

All is quiet and still. The Deep Ones will vanish and the storm will finally cease. The water that was gathering in the valley will eventually drain away, though it will take most of the day. There isn't much cause for celebration however, in the coming days only a handful of survivors will be found in poor health and worse mental state. The once busy town will be no more and few will know what really happen.


** HANDOUTS

** LICENSE

 2015 ~ Chris Hardee <shazzner@gmail.com>
This work is licensed under Creative Commons BY-NC-SA [http://creativecommons.org/licenses/by-nc-sa/3.0/]

*** Contributing

Contributions are welcome to this work, if you have any issues ranging from misspelled words, grammatical and/or syntax problems, gameplay balance issues, etc. Please file an issue on github.

*** Translations

Help translate this work into multiple languages! If you would like to please email me and I can help you add your translation to the main repository.

** TODOs
- replace check with roll for skill rolls

